# app/service/interview_question.py
import openai
import dotenv
import os

dotenv.load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

def generate_interview_questions_from_skills(skills: list) -> list:
    """
    This function takes a list of skills and returns a list of interview questions
    generated by GPT-4 based on those skills.
    """
    if not skills:
        raise ValueError("No skills provided")

    prompt = f"Generate interview questions based on the following skills: {', '.join(skills)}."

    try:
        response = openai.Completion.create(
            engine="gpt-4",  # Use GPT-4
            prompt=prompt,
            max_tokens=150,
            temperature=0.7,
        )

        questions = response.choices[0].text.strip().split('\n')  # Assuming each question is on a new line
        return questions

    except Exception as e:
        raise Exception(f"Error generating interview questions: {str(e)}")
