version: "3.9"

volumes:
  data:

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  migration:
    container_name: migration
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.migrate
    command: upgrade head
    depends_on:
      - postgres
    profiles:
      - migration