FROM python:3.10.5

WORKDIR /app

RUN apt-get update && apt-get -y install \
    libssl-dev \ 
    libffi-dev \
    libsasl2-dev \ 
    libldap2-dev \
    libgl1-mesa-glx \
    ffmpeg


COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]