FROM python:3.10.5

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    libffi-dev \
    libblas-dev \
    liblapack-dev \
    libopenblas-dev \
    libatlas-base-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    python3-dev \
    python3-pip \
    make \
    libstdc++6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV BLIS_ARCH="generic"

COPY requirements.txt .
RUN pip install --upgrade pip==24.0 && \
    pip install -r requirements.txt

COPY . .

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]