FROM python:3.10.5

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    python3-dev \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV BLIS_ARCH="generic"

COPY requirements.txt .
RUN pip install --upgrade pip==24.0 && \
    pip install -r requirements.txt

COPY alembic.ini .
COPY alembic ./alembic
COPY app/db.py ./app/db.py

ENTRYPOINT ["alembic"]
CMD ["upgrade", "head"]