[phases.setup]
apt_packages = [
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender1",
  "libpq5"
]

[phases.build]
commands = [
  "pip install --upgrade pip==24.0",
  "pip install -r requirements.txt"
]