"""edit models

Revision ID: 04ad35770a31
Revises: 6d6a97f332d5
Create Date: 2025-03-05 17:53:07.037295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ad35770a31'
down_revision: Union[str, None] = '6d6a97f332d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('mock_interview', sa.Column('job_position', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_interview', 'job_position')
    op.drop_column('mock_interview', 'company_name')
    # ### end Alembic commands ###
