"""add summary field on subcategory

Revision ID: 10ffc188d48f
Revises: c78daccf99c0
Create Date: 2025-03-17 06:52:22.068981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ffc188d48f'
down_revision: Union[str, None] = 'c78daccf99c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory', 'summary')
    # ### end Alembic commands ###
