"""create users_resume table

Revision ID: 13b67e025dda
Revises: 52deef494495
Create Date: 2025-03-28 18:09:51.746773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13b67e025dda'
down_revision: Union[str, None] = '52deef494495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_resume',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_extracted', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_resume')
    # ### end Alembic commands ###
