"""add unique constraint

Revision ID: 3d71c7e635cb
Revises: 543b4c7daa68
Create Date: 2025-03-21 20:47:57.207850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d71c7e635cb'
down_revision: Union[str, None] = '543b4c7daa68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_job_user', 'mock_interview', ['job_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_job_user', 'mock_interview', type_='unique')
    # ### end Alembic commands ###
