"""added job position and company column on Course model

Revision ID: 52deef494495
Revises: 3d71c7e635cb
Create Date: 2025-03-22 08:44:12.249413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52deef494495'
down_revision: Union[str, None] = '3d71c7e635cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('job_position', sa.String(), nullable=False))
    op.add_column('course', sa.Column('company_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'company_name')
    op.drop_column('course', 'job_position')
    # ### end Alembic commands ###
