"""add video id column on chapter

Revision ID: 543b4c7daa68
Revises: 9bb9a6757ca7
Create Date: 2025-03-19 04:01:39.902552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543b4c7daa68'
down_revision: Union[str, None] = '9bb9a6757ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('video_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'video_id')
    # ### end Alembic commands ###
