"""add new tables

Revision ID: 6d6a97f332d5
Revises: d30d73d20fed
Create Date: 2025-03-05 13:46:11.830796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6a97f332d5'
down_revision: Union[str, None] = 'd30d73d20fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview',
    sa.Column('mock_interview_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mock_interview_id')
    )
    op.create_index(op.f('ix_mock_interview_mock_interview_id'), 'mock_interview', ['mock_interview_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('mock_interview_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mock_interview_id'], ['mock_interview.mock_interview_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=False)
    op.create_table('subcategory',
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('subcategory_id')
    )
    op.create_index(op.f('ix_subcategory_subcategory_id'), 'subcategory', ['subcategory_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.subcategory_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    op.drop_index('ix_skills_skill_id', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('skill_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skill_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('skill_id', name='skills_pkey')
    )
    op.create_index('ix_skills_skill_id', 'skills', ['skill_id'], unique=False)
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_subcategory_subcategory_id'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_mock_interview_mock_interview_id'), table_name='mock_interview')
    op.drop_table('mock_interview')
    # ### end Alembic commands ###
