"""add course chapter and unit table

Revision ID: 73c5b8f83ebb
Revises: 2ae01e17e1c6
Create Date: 2025-03-19 02:15:39.618433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c5b8f83ebb'
down_revision: Union[str, None] = '2ae01e17e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_unit_unit_id'), 'unit', ['unit_id'], unique=False)
    op.create_table('chapter',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('video_thumbnail', sa.String(), nullable=True),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.Column('video_transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_index(op.f('ix_chapter_chapter_id'), 'chapter', ['chapter_id'], unique=False)
    op.drop_index('ix_course_subtopic_course_subtopic_id', table_name='course_subtopic')
    op.drop_table('course_subtopic')
    op.add_column('course', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'image_url')
    op.create_table('course_subtopic',
    sa.Column('course_subtopic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='course_subtopic_course_id_fkey'),
    sa.PrimaryKeyConstraint('course_subtopic_id', name='course_subtopic_pkey')
    )
    op.create_index('ix_course_subtopic_course_subtopic_id', 'course_subtopic', ['course_subtopic_id'], unique=False)
    op.drop_index(op.f('ix_chapter_chapter_id'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_unit_unit_id'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
