"""add unit name in course

Revision ID: 9bb9a6757ca7
Revises: eef08a0eae1d
Create Date: 2025-03-19 03:21:55.801389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb9a6757ca7'
down_revision: Union[str, None] = 'eef08a0eae1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('unit_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'unit_name')
    # ### end Alembic commands ###
