"""add new column status

Revision ID: c38b8e6b015e
Revises: cfb69fbe8c98
Create Date: 2025-03-07 15:11:01.114762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38b8e6b015e'
down_revision: Union[str, None] = 'cfb69fbe8c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory', 'status')
    # ### end Alembic commands ###
