"""course and subtopic model

Revision ID: c78daccf99c0
Revises: e6eadf7e51a2
Create Date: 2025-03-17 06:45:10.920593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78daccf99c0'
down_revision: Union[str, None] = 'e6eadf7e51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('mock_interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_interview_id'], ['mock_interview.mock_interview_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_course_id'), 'course', ['course_id'], unique=False)
    op.create_table('course_subtopic',
    sa.Column('course_subtopic_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('course_subtopic_id')
    )
    op.create_index(op.f('ix_course_subtopic_course_subtopic_id'), 'course_subtopic', ['course_subtopic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_subtopic_course_subtopic_id'), table_name='course_subtopic')
    op.drop_table('course_subtopic')
    op.drop_index(op.f('ix_course_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
