"""add feedback field

Revision ID: c8afee19fc42
Revises: 00c526cc9f13
Create Date: 2025-04-19 18:16:18.466600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8afee19fc42'
down_revision: Union[str, None] = '00c526cc9f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_interview_questions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_interview_questions', 'feedback')
    # ### end Alembic commands ###
