"""added column

Revision ID: d30d73d20fed
Revises: 3f03a6fa9193
Create Date: 2025-03-05 10:19:08.175660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30d73d20fed'
down_revision: Union[str, None] = '3f03a6fa9193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skill_category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skill_category')
    # ### end Alembic commands ###
