"""add user id field on course

Revision ID: eef08a0eae1d
Revises: 73c5b8f83ebb
Create Date: 2025-03-19 02:25:54.224493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef08a0eae1d'
down_revision: Union[str, None] = '73c5b8f83ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'user_id')
    # ### end Alembic commands ###
